name: 할일 정하기 💡
description: 오늘 할 일을 간단히 정리해보세요.
title: "[Todo] "
labels: ["todo", "planning"]

body:
  - type: input
    id: date
    attributes:
      label: 오늘 날짜는?
      placeholder: 예) 2025-06-30
    validations:
      required: true
  
  - type: input
    id: branch-name
    attributes:
      label: 작업 중인 브랜치 이름은?
      placeholder: 예) feat/signup-auth-flow
    validations:
      required: false

  - type: textarea
    id: todo-list
    attributes:
      label: 오늘의 할 일 목록은 무엇인가요 ?
      placeholder: 예)
        - 프로젝트 폴더링 정리
        - MVVM 구조 리팩토링
        - Firebase 인증 흐름 연결
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: 느낀 점 / 내일 할 일
      placeholder: 예) 이해는 됐지만 코드 구현이 부족함 → 내일은 실제 예제로 연습